config/routes.rb
Rails.application.routes.draw do

  devise_config = ActiveAdmin::Devise.config
  devise_config[:controllers][:omniauth_callbacks] = 'users/omniauth_callbacks'
  devise_for :users, devise_config

  ActiveAdmin.routes(self)
  resources :episodes, only: [:index, :show] do
    collection do
      get '/search', to: 'episodes#search'
    end
  end
  get 'playlist/:id', to: 'episodes#playlist', as: 'playlist'
  get 'conference/:id', to: 'episodes#playlist', as: 'conference'
  get 'feed', to: 'episodes#index', format: 'atom'

  resources :organizations, only: [:index]
  resources :subscribers, only: [:create]

  root 'welcome#index'
  get 'about' => 'welcome#about'
  get 'events' => 'welcome#events'
  get 'cal' => 'welcome#cal'
  get 'conferences' => 'welcome#conferences'
  get 'bookings' => 'welcome#bookings'
  get 'live' => 'welcome#live'
  get 'fb_live' => 'welcome#fb_live'
  get 'support_us' => 'welcome#support_us'
  get 'screenshots' => 'welcome#screenshots'
  get 'terms' => 'welcome#terms'

  get 'videos/:tag', to: 'episodes#index', as: :tag
  get 'v/:id', to: 'episodes#alias', as: 'video'
  get 'video/*title--:id', to: 'episodes#show', as: 'video_slug'
  get ':id', to: 'episodes#show', as: 'video_shortcut', constraints: { id: /[0-9]+/ }

  get 'presenters', to: 'presenters#index', as: 'presenters'
  get 'presenters/search', to: 'presenters#search', as: 'presenters_search'
  get 'presenters/:id', to: 'presenters#alias', as: 'presenter'
  get 's/:id', to: redirect('/presenter/%{id}'), as: 'speaker'
  get 'presenter/*name--:id', to: 'presenters#show', as: 'presenter_name_slug'
  get 'presenter/:id', to: 'presenters#slug', as: 'presenter_slug'

  get '/video/new-directions-in-cryptography-papers-we-love', to: redirect('/video/new-directions-in-cryptography-papers-we-love--601')

  get 'organization/*name--:id', to: 'organizations#show', as: 'organization_name'
  get 'organizations/:id', to: 'organizations#alias', as: 'organization_show', constraints: { id: /[0-9]+/ }
  get 'organization/:id', to: 'organizations#alias', as: 'organization_alias', constraints: { id: /[0-9]+/ }
  get 'org/:id', to: 'organizations#alias', constraints: { id: /[0-9]+/ }
  get 'o/:id', to: 'organizations#alias', constraints: { id: /[0-9]+/ }
  get 'organizations/:id', to: 'organizations#show', as: 'organization_show_slug'
  get 'organization/:id', to: 'organizations#show', as: 'organization_slug'

  scope :api, defaults: {format: :json} do
    get '/organizations', to: 'api#organizations'
    get '/organization/:id', to: 'api#organization'
    get '/organization/:id/videos', to: 'api#organization_videos'
    get '/presenters', to: 'api#presenters'
    get '/events', to: 'api#events'
  end

  if Rails.env.development?
    get 'googleauth/start', to: 'google_auth#start'
    get 'googleauth/callback', to: 'google_auth#callback'
  end
end

app/models/episode.rb
class Episode < ApplicationRecord
  acts_as_taggable

  enum video_site: { youtube: 1, vimeo: 2 }

  has_many :playlist_items, dependent: :destroy
  has_many :playlists, through: :playlist_items
  has_many :video_organizations, dependent: :destroy
  has_many :organizations, through: :video_organizations
  has_many :video_presenters, dependent: :destroy
  has_many :presenters, through: :video_presenters
  has_many :video_links, dependent: :destroy
  has_many :featured_videos, dependent: :destroy

  accepts_nested_attributes_for :video_organizations, allow_destroy: true
  accepts_nested_attributes_for :video_presenters, allow_destroy: true
  accepts_nested_attributes_for :video_links, allow_destroy: true

  scope :active, -> { where(active: true) }

  before_validation :pull_video_info

  def pull_video_info
    if video_id.present? && video_site.present? && title.blank?
      if (video_site == 'vimeo')
        video_info = VimeoService.new.get_video(video_id)
      elsif (video_site == 'youtube')
        video_info = YoutubeService.new(access_token: ENV["YOUTUBE_ACCESS_TOKEN"], refresh_token: ENV["YOUTUBE_REFRESH_TOKEN"]).get_video(video_id)
      end

      if video_info.present?
        assign_attributes(
          title: video_info.title,
          published_at: video_info.published_at,
          description: video_info.description,
          image1: video_info.image1,
          image2: video_info.image2,
          image3: video_info.image3
        )
      end
    end
  end

end

app/controllers/episodes_controller.rb
class EpisodesController < ApplicationController
  def index
    @episodes = Episode.active.tagged_with(params[:tag]) if params[:tag]
    @episodes ||= Episode.active.all
    @current_page = (params[:page] || 1).to_i
    @episodes = @episodes.active.order('published_at DESC').page(@current_page)
    @total_records = @episodes.total_count
  end

  def playlist
    @playlist = is_number?(params[:id]) ? Playlist.find(params[:id]) : Playlist.find_by_slug(params[:id])
    @episodes = @playlist.playlist_items.order('sort_order ASC').map(&:episode).select{|episode| episode.active? }
  end

  def search
    @search = search_param[:search]
    @episodes = @search.present? ? Episode.active.where("lower(title) like :term or lower(description) like :term", {term: "%#{@search.downcase}%"}).order('published_at DESC') : []
  end

  def show
    @video = Episode.active.find(params[:id])
  end

  def alias
    @video = Episode.active.find(params[:id])
    redirect_to video_slug_path(title: @video.title.parameterize, id: @video.id)
  end

  private

  def search_param
    params.permit(:search)
  end
end

app/helpers/episodes_helper.rb
module EpisodesHelper
end

app/views/episodes/index.html.slim
==render partial: 'shared/default_social_share_headers'

.container
  .row
    .col.s12
      h4 All Videos
      p Listing of the videos we record at local tech meetups/events.
    .col.s12
      h5= "#{@total_records} videos found."
      p=page_entries_info @episodes, :entry_name => 'video'
  .videos.row
    == render partial: 'shared/video', collection: @episodes, as: :video

  .row
    .col.s12
      ul.pagination.center
        - if @current_page<2
          li.disabled
            a href='#!'
              i.material-icons chevron_left
        - else
          li.waves-effect
            a href=episodes_path(page:@current_page-1)
              i.material-icons chevron_left

        - (1..@episodes.total_pages).each do |n|
          li class=(n==@current_page ? 'active' : 'waves-effect')
            a(href=episodes_path(page:n))= n

        - if @current_page >= @episodes.total_pages
          li.disabled
            a href='#!'
              i.material-icons chevron_right
        - else
          li.waves-effect
            a href=episodes_path(page:@current_page+1)
              i.material-icons chevron_right

app/views/episodes/playlist.html.slim
- content_for :social_share_headers do
  meta property="og:site_name" content="Engineers.SG"
  meta property="og:title" content="Playlist: #{@playlist.name} - Engineers.SG" /
  meta property="og:description" content=@playlist.description /
  meta property="og:url" content=playlist_url(@playlist) /
  meta property="og:image" content=@playlist.image /
  meta property="og:type" content="website" /
  meta property="fb:app_id" content="1636558033282778" /

  meta name="twitter:card" content="summary" /
  meta name="twitter:site" content="@engineersftw" /
  meta name="twitter:title" content="Playlist: #{@playlist.name} - Engineers.SG" /
  meta name="twitter:description" content=@playlist.description /
  meta name="twitter:image" content=@playlist.image /

.container
  .row
    .col.s12
      h4= @playlist.name
      p=auto_link(simple_format(@playlist.description))
    - if @playlist.sub_playlists.present?
      .col.s12
        ul
          - @playlist.conference_tracks.each do |track|
            li
              = link_to track.name, playlist_path( track.slug.present? ? track.slug : track.id )
    .col.s12
      h5= "#{@episodes.count} videos found."
  .videos.row
    == render partial: 'shared/video', collection: @episodes, as: :video

app/views/episodes/search.html.slim
==render partial: 'shared/default_social_share_headers'

.container
  .row
    .col.s12
      h4 Search Videos
      form.row method="get" action="/episodes/search"
        .col.s12.input-field
          label for="search_field" Keyword
          input id="search_field" type="text" name="search" value=@search
          button.btn.waves-effect.waves-light Go
  - unless @episodes.empty?
    .row
      .col.s12
        h5= "#{@episodes.count} videos found."
    .videos.row
      == render partial: 'shared/video', collection: @episodes, as: :video

app/views/episodes/show.html.slim
- content_for :social_share_headers do
  meta property="og:site_name" content="Engineers.SG"
  meta property="og:title" content="#{@video.title} - Engineers.SG" /
  meta property="og:description" content=@video.description /
  meta property="og:url" content=video_slug_url(title: @video.title.parameterize, id: @video.id) /
  meta property="og:image" content=@video.image3 /
  meta property="og:type" content="website" /
  meta property="fb:app_id" content="1636558033282778" /

  meta name="twitter:card" content="summary" /
  meta name="twitter:site" content="@engineersftw" /
  meta name="twitter:title" content="#{@video.title} - Engineers.SG" /
  meta name="twitter:description" content=@video.description /
  meta name="twitter:image" content=@video.image3 /

  link rel="canonical" href=video_slug_url(title: @video.title.parameterize, id: @video.id) /

.container
  .row
    .col.s12
      h4=@video.title
  .row
    .col.s12 class=(Feature.active?(:video_sidebar) && (@video.organizations.present? || @video.organizations.present? || @video.video_links.present?) ? 'l10' : 'l12' )
      .row
        .col.s12
          .video.video-container
            - if @video.video_site == 'youtube'
              #player
            - elsif @video.video_site == 'vimeo'
              iframe allowfullscreen=true frameborder="0" height="281" src="https://player.vimeo.com/video/#{@video.video_id}" width="500"
      .row
        .col.s12.m6.share-stats
          .share-btn
            span.youtube-view-count= "#{@video.view_count} views"
          .share-btn.fb
            .fb-share-button data-href=episode_url(@video) data-layout="button_count"
          .share-btn
            a.twitter-share-button data-text="#{twitter_share_text(@video)}" data-url=episode_url(@video) href="https://twitter.com/share" Tweet
        .col.s12.m6.right-align
          span.sponsor
            | Benefitted from this video? &nbsp;
            = link_to 'Click here to Support our efforts', support_us_path

        .col.s12
          strong
            | Published on:
            =< @video.published_at.strftime('%A, %e %B %Y')
        .col.s12
          = auto_link(simple_format(@video.description))
        .col.s12
          a(href="javascript:window.history.back()") &laquo; Back

    - if Feature.active?(:video_sidebar) && (@video.organizations.present? || @video.organizations.present? || @video.video_links.present?)
      .col.s12.l2
        .row
          - if @video.organizations.present?
            .col.s6.l12
              h5 Organization
              ul
                - @video.organizations.each do |organization|
                  li
                    a href=organization_alias_path(organization)
                      - if organization.image.present?
                        img.responsive-img src=organization.image
                        br
                      = organization.title
          - if @video.presenters.present?
            .col.s6.l12
              h5 Presenter
              ul
                - @video.presenters.each do |presenter|
                  li
                    a href=(presenter.twitter.present? ? speaker_path(presenter.twitter) : presenter_path(presenter))
                      - if presenter.avatar.present?
                        img.responsive-img src=presenter.avatar
                        br
                      =presenter.name
          - if @video.video_links.present?
            .col.s12
              h5 Links
              ul
                - @video.video_links.each do |link|
                  li
                    a href=link.url target="_blank" =link.title
          - if @video.tag_list.present?
            .col.s12
              h5 Tags
              p= raw @video.tag_list.map { |t| link_to t, tag_path(t) }.join(', ')


  .row
    .col.s12.m12.l10
      .fb-comments data-href=video_url(@video) data-numposts="5" data-mobile="true"

javascript:
  var tag = document.createElement('script');

  tag.src = "https://www.youtube.com/iframe_api";
  var firstScriptTag = document.getElementsByTagName('script')[0];
  firstScriptTag.parentNode.insertBefore(tag, firstScriptTag);

  var player;
  function onYouTubeIframeAPIReady() {
    player = new YT.Player('player', {
      height: '486',
      width: '864',
      videoId: '#{@video.video_id}',
      playerVars: { 'rel': 0, 'modestbranding': 1, 'ytp-pause-overlay': 0 },
      events: {
        'onStateChange': onPlayerStateChange
      }
    });
  }

  var started_playing = false
  function onPlayerStateChange(event) {
    if (event.data < 0) {
      ga('send', 'event', 'Videos', 'loaded', '#{@video.title}', #{@video.id});
    }
    if (event.data == YT.PlayerState.PLAYING) {
      if (!started_playing) {
        ga('send', 'event', 'Videos', 'started_play', '#{@video.title}', #{@video.id});
        started_playing = true;
      }
    }
    if (event.data == YT.PlayerState.ENDED) {
      ga('send', 'event', 'Videos', 'ended', '#{@video.title}', #{@video.id});
    }
  }

app/views/episodes/tags.html.slim
- content_for :social_share_headers do
  meta property="og:site_name" content="Engineers.SG"
  meta property="og:title" content="Playlist: #{@playlist.name} - Engineers.SG" /
  meta property="og:description" content=@playlist.description /
  meta property="og:url" content=playlist_url(@playlist) /
  meta property="og:image" content=@playlist.image /
  meta property="og:type" content="website" /
  meta property="fb:app_id" content="1636558033282778" /

  meta name="twitter:card" content="summary" /
  meta name="twitter:site" content="@engineersftw" /
  meta name="twitter:title" content="Playlist: #{@playlist.name} - Engineers.SG" /
  meta name="twitter:description" content=@playlist.description /
  meta name="twitter:image" content=@playlist.image /

.container
  .row
    .col.s12
      h4= @playlist.name
      p=@playlist.description
    .col.s12
      h5= "#{@episodes.count} videos found."
  .videos.row
    == render partial: 'shared/video', collection: @episodes, as: :video